name: basalt
channels:
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/bioconda
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/r
  - esteinig
  # Remove 'defaults', 'conda-forge', 'bioconda' (the non-mirror versions)
  # Remove the 'freeru' line
dependencies:
  - python=3.12
  # --- Bioinformatics Tools ---
  - megahit
  - metabat2
  - maxbin2
  - concoct
  - prodigal
  - semibin
  - bedtools
  - blast
  - bowtie2
  - diamond
  - checkm2             
  - checkm-genome     
  - unicycler
  - spades
  - samtools
  - racon
  - pplacer
  - pilon
  - ncbi-vdb
  - minimap2
  - miniasm
  - idba
  - hmmer
  - entrez-direct
  - biopython          
  # --- System/Build Tools ---
  - pip
  - uv                 
  # --- Pip Dependencies ---
  - pip:
      - tensorflow
      - torch
      - torchvision
      - tensorboard
      - tensorboardx
      - lightgbm
      - scikit-learn
      - numpy
      - scipy
      - pandas
      - matplotlib
      - cython
      - biolib
      - joblib
      - tqdm
      - requests
